[workspace]
resolver = "2"
members = [
    "crates/combinator-core",
    "crates/combinator-codecs",
    "crates/combinator-app",
    "crates/combinator-cli",
    "crates/combinator-gui",
    "crates/combinator-tui",
    "crates/combinator-benchmarks",
]
exclude = ["fuzz"]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"
