[package]
name = "combinator-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
combinator-codecs = { path = "../crates/combinator-codecs" }
serde_json = "1"

[[bin]]
name = "inline"
path = "fuzz_targets/inline.rs"
test = false
doc = false
bench = false

[[bin]]
name = "template"
path = "fuzz_targets/template.rs"
test = false
doc = false
bench = false

[[bin]]
name = "join_jsonl"
path = "fuzz_targets/join_jsonl.rs"
test = false
doc = false
bench = false

[[bin]]
name = "output"
path = "fuzz_targets/output.rs"
test = false
doc = false
bench = false
