//! UI-neutral application workflows shared by the CLI, GUI, and TUI.
//!
//! This crate owns request validation, planning, bounded preview generation,
//! and execution orchestration. It deliberately has no dependency on Clap,
//! terminals, windows, processes, or filesystem paths.

mod file_sink;
mod join;

use combinator_codecs::{InputBudget, SizeEstimate, SizeInput};
use combinator_core::{
    generate_with, Constraint, CoreError, Count, GenerationLimits, GenerationRequest, Operation,
    ProductOptions, SelectionOptions, ZipOptions,
};
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};

pub use combinator_codecs::{Format, InputFormat, InputLimits};
pub use combinator_core::UnequalPolicy;

/// User-selectable generation operation exposed by the application surfaces.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AppOperation {
    Product { reverse_fields: bool },
    Zip { on_unequal: UnequalPolicy },
    Concat,
    Permutations,
    Combinations { choose: usize },
    Variations { length: usize },
}

impl Default for AppOperation {
    fn default() -> Self {
        Self::Product {
            reverse_fields: false,
        }
    }
}

/// A Product request in the initial application workflow.
#[derive(Debug, Clone)]
pub struct ProductRequest {
    /// Input lists in their visible, user-defined order.
    pub lists: Vec<Vec<String>>,
    /// Text inserted between fields in one generated value.
    pub field_separator: String,
    /// Text inserted after each text record.
    pub record_separator: String,
    /// Output encoding used by preview and execution.
    pub format: Format,
    /// Emit only JSON string values when using JSONL.
    pub lean_jsonl: bool,
    /// Product traversal options.
    pub options: ProductOptions,
    /// Generation operation selected by the user interface.
    pub operation: AppOperation,
    /// Optional names aligned with input lists for named templates/JSONL.
    pub names: Vec<String>,
    /// Maximum records generated by one operation.
    pub max_combinations: u128,
    /// Maximum encoded bytes generated by one operation.
    pub max_output_bytes: u128,
    /// Maximum bytes read from each input source.
    pub max_input_bytes: usize,
    /// Maximum number of input lists accepted by the application workflow.
    pub max_lists: usize,
    /// Maximum items accepted in one input list.
    pub max_items_per_list: usize,
    /// Maximum total items accepted across all input lists.
    pub max_total_items: usize,
    /// Maximum UTF-8 bytes accepted in one input item.
    pub max_item_bytes: usize,
    /// Optional bounded template applied to each generated record.
    pub template: Option<String>,
    /// Optional bounded UTF-8 file containing the output template.
    pub template_file: Option<String>,
    /// Repeated deterministic transform expressions applied in order.
    pub transforms: Vec<String>,
    /// Repeated typed candidate filters, using the CLI expression syntax.
    pub filters: Vec<String>,
    /// Optional wall-clock execution deadline for background callers.
    pub timeout_ms: Option<u64>,
    /// Optional zero-based contiguous shard index and total shard count.
    pub shard_index: Option<u128>,
    pub shard_count: Option<u128>,
}

impl Default for ProductRequest {
    fn default() -> Self {
        Self {
            lists: Vec::new(),
            field_separator: String::new(),
            record_separator: "\n".to_string(),
            format: Format::Text,
            lean_jsonl: false,
            options: ProductOptions::default(),
            operation: AppOperation::default(),
            names: Vec::new(),
            max_combinations: 10_000_000,
            max_output_bytes: 1_073_741_824,
            max_input_bytes: 64 * 1024 * 1024,
            max_lists: 128,
            max_items_per_list: 1_000_000,
            max_total_items: 5_000_000,
            max_item_bytes: 1_048_576,
            template: None,
            template_file: None,
            transforms: Vec::new(),
            filters: Vec::new(),
            timeout_ms: None,
            shard_index: None,
            shard_count: None,
        }
    }
}

/// A validated request summary suitable for a plan panel.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExecutionPlan {
    pub list_lengths: Vec<usize>,
    pub total_combinations: Count,
    pub records_to_emit: u128,
    pub estimated_output_bytes: SizeEstimate,
    pub warnings: Vec<Warning>,
}

/// A non-fatal condition the user may choose to acknowledge.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Warning {
    pub code: &'static str,
    pub message: &'static str,
}

/// A bounded source for one logical input list.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InputSource {
    Inline { value: String, delimiter: String },
    File { path: String, format: InputFormat },
}

/// Loads one input source using the same bounded codecs as the CLI.
pub fn read_input_source(
    source: &InputSource,
    limits: InputLimits,
) -> Result<Vec<String>, AppError> {
    let mut budget = InputBudget::new(limits.max_input_bytes, limits.max_items_per_list);
    match source {
        InputSource::Inline { value, delimiter } => {
            combinator_codecs::input::split_inline(value, delimiter, limits, &mut budget)
                .map_err(codec_error)
        }
        InputSource::File { path, format } => {
            let file = std::fs::File::open(path).map_err(|error| {
                AppError::runtime(
                    "FILE_UNREADABLE",
                    format!("could not read input file: {error}"),
                )
            })?;
            combinator_codecs::input::read_formatted(file, path, *format, limits, &mut budget)
                .map_err(codec_error)
        }
    }
}

fn codec_error(error: combinator_codecs::CodecError) -> AppError {
    AppError {
        code: error.code,
        message: error.message,
    }
}

/// One rendered record delivered to an application sink.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OutputRecord {
    pub ordinal: u128,
    pub value: String,
    pub fields: Vec<String>,
}

/// Compatibility name for records returned by the bounded preview helper.
pub type PreviewRecord = OutputRecord;

pub use file_sink::FileSink;
pub use join::{join_plan, join_preview, join_stream, JoinFormat, JoinKind, JoinPlan, JoinRequest};

/// Progress information emitted after a record is accepted by a sink.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProgressEvent {
    pub records: u128,
    pub bytes: u128,
}

/// Destination abstraction shared by file, GUI, TUI, and preview consumers.
pub trait OutputSink {
    fn record(&mut self, record: OutputRecord) -> Result<(), AppError>;

    fn progress(&mut self, _event: ProgressEvent) -> Result<(), AppError> {
        Ok(())
    }
}

/// Thread-safe cancellation signal for background generation.
#[derive(Debug, Clone, Default)]
pub struct CancellationToken {
    cancelled: Arc<AtomicBool>,
}

impl CancellationToken {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn cancel(&self) {
        self.cancelled.store(true, Ordering::Release);
    }

    pub fn is_cancelled(&self) -> bool {
        self.cancelled.load(Ordering::Acquire)
    }
}

/// Errors exposed to any first-party interface.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AppError {
    pub code: &'static str,
    pub message: String,
}

impl AppError {
    fn usage(code: &'static str, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }

    fn runtime(code: &'static str, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }
}

impl From<CoreError> for AppError {
    fn from(error: CoreError) -> Self {
        Self {
            code: error.code,
            message: error.message,
        }
    }
}

impl From<combinator_codecs::template::TemplateError> for AppError {
    fn from(error: combinator_codecs::template::TemplateError) -> Self {
        Self {
            code: "TEMPLATE_INVALID",
            message: format!("invalid output template: {error:?}"),
        }
    }
}

/// Plans a Product request without generating records.
pub fn plan(request: &ProductRequest) -> Result<ExecutionPlan, AppError> {
    validate_request(request)?;
    let lists = prepared_lists(request)?;
    let operation = core_operation(request);
    let total_combinations = combinator_core::operation_count(&operation, &lists)
        .map_err(|_| AppError::usage("ZIP_LENGTH_MISMATCH", "zip inputs have unequal lengths"))?;
    let operation = apply_shard(request, operation, total_combinations)?;
    let records_to_emit = operation_selected_count(total_combinations, &operation);
    let estimated_output_bytes = match request.format {
        Format::Jsonl => combinator_codecs::estimate_jsonl_size(
            &SizeInput {
                lists: &lists,
                field_sep_bytes: request.field_separator.len() as u64,
                rec_sep_bytes: 1,
            },
            request.lean_jsonl,
        ),
        Format::Text | Format::Csv | Format::Tsv | Format::Nul => {
            combinator_codecs::estimate_text_size(&SizeInput {
                lists: &lists,
                field_sep_bytes: request.field_separator.len() as u64,
                rec_sep_bytes: request.record_separator.len() as u64,
            })
        }
    };
    // Concat emits each list in sequence, so an empty list drops out without
    // affecting the records the other lists contribute.
    let empty_list_message = match request.operation {
        AppOperation::Concat => "an input list is empty; it contributes no records",
        _ => "an input list is empty; no records will be generated",
    };
    let warnings = request
        .lists
        .iter()
        .filter(|list| list.is_empty())
        .map(|_| Warning {
            code: "EMPTY_LIST",
            message: empty_list_message,
        })
        .collect();
    Ok(ExecutionPlan {
        list_lengths: lists.iter().map(Vec::len).collect(),
        total_combinations,
        records_to_emit,
        estimated_output_bytes,
        warnings,
    })
}

/// Generates a bounded preview without changing the request's full plan.
pub fn preview(
    request: &ProductRequest,
    preview_limit: u128,
) -> Result<Vec<PreviewRecord>, AppError> {
    let mut request = request.clone();
    request.options.offset = 0;
    request.options.limit = Some(preview_limit);
    execute(&request)
}

/// Streams a Product request to a caller-provided sink.
pub fn stream<S: OutputSink>(
    request: &ProductRequest,
    sink: &mut S,
    cancel: Option<&dyn Fn() -> bool>,
) -> Result<ProgressEvent, AppError> {
    let plan = plan(request)?;
    let lists = prepared_lists(request)?;
    if plan.records_to_emit > request.max_combinations {
        return Err(AppError {
            code: "COMBINATION_LIMIT_EXCEEDED",
            message: "requested combinations exceed the configured generation limit".to_string(),
        });
    }
    let operation = apply_shard(request, core_operation(request), plan.total_combinations)?;
    let constraints = parse_filters(&request.filters)?;
    let template_source = resolved_template(request)?;
    let template = template_source
        .as_deref()
        .map(combinator_codecs::Template::parse)
        .transpose()
        .map_err(|error| AppError::usage("TEMPLATE_INVALID", format!("{error:?}")))?;
    let started = std::time::Instant::now();
    let timeout_ms = request.timeout_ms;
    let timed_cancel = || {
        cancel.is_some_and(|cancel| cancel())
            || timeout_ms.is_some_and(|limit| started.elapsed().as_millis() >= u128::from(limit))
    };
    let generation = GenerationRequest {
        operation: &operation,
        lists: &lists,
        constraints: &constraints,
        limits: GenerationLimits {
            max_combinations: request.max_combinations,
        },
        cancel: Some(&timed_cancel),
    };
    let mut progress = ProgressEvent {
        records: 0,
        bytes: 0,
    };
    generate_with(generation, |record| {
        let fields = record
            .fields
            .iter()
            .map(|(list, item)| lists[*list][*item].clone())
            .collect::<Vec<_>>();
        let refs = fields.iter().map(String::as_str).collect::<Vec<_>>();
        let encoded = combinator_codecs::format_record_with(
            &refs,
            record.ordinal,
            &request.field_separator,
            &request.record_separator,
            request.format,
            request.lean_jsonl,
            template.as_ref(),
            &request.names,
        )
        .map_err(|error| CoreError::usage("TEMPLATE_INVALID", format!("{error:?}")))?;
        progress.bytes = progress
            .bytes
            .checked_add(encoded.len() as u128)
            .ok_or_else(|| {
                CoreError::runtime("OUTPUT_LIMIT_EXCEEDED", "output byte count overflowed")
            })?;
        if progress.bytes > request.max_output_bytes {
            return Err(CoreError::runtime(
                "OUTPUT_LIMIT_EXCEEDED",
                "output exceeds the configured byte limit",
            ));
        }
        sink.record(OutputRecord {
            ordinal: record.ordinal,
            value: encoded,
            fields,
        })
        .map_err(|error| CoreError::runtime(error.code, error.message))?;
        progress.records = progress.records.checked_add(1).ok_or_else(|| {
            CoreError::runtime("OUTPUT_LIMIT_EXCEEDED", "output record count overflowed")
        })?;
        sink.progress(progress)
            .map_err(|error| CoreError::runtime(error.code, error.message))?;
        Ok(())
    })
    .map_err(AppError::from)?;
    Ok(progress)
}

/// Executes a Product request and returns encoded records in memory.
///
/// This is primarily a convenience for bounded previews. Large or persistent
/// output should use [`stream`] with a bounded sink instead.
pub fn execute(request: &ProductRequest) -> Result<Vec<PreviewRecord>, AppError> {
    struct Collector {
        records: Vec<OutputRecord>,
    }

    impl OutputSink for Collector {
        fn record(&mut self, record: OutputRecord) -> Result<(), AppError> {
            self.records.push(record);
            Ok(())
        }
    }

    let mut collector = Collector {
        records: Vec::new(),
    };
    stream(request, &mut collector, None)?;
    Ok(collector.records)
}

fn validate_request(request: &ProductRequest) -> Result<(), AppError> {
    if request.lists.is_empty() {
        return Err(AppError::usage("NO_LISTS", "no input lists were provided"));
    }
    if request.transforms.len() > combinator_core::normalize::MAX_TRANSFORMS {
        return Err(AppError::usage(
            "TRANSFORM_LIMIT",
            "the number of transforms exceeds the security limit",
        ));
    }
    parse_filters(&request.filters)?;
    if request.lists.len() > request.max_lists {
        return Err(AppError::usage(
            "TOO_MANY_LISTS",
            "input exceeds the configured list limit",
        ));
    }
    let mut total_items = 0usize;
    for list in &request.lists {
        if list.len() > request.max_items_per_list {
            return Err(AppError::usage(
                "TOO_MANY_ITEMS",
                "input list exceeds the configured item limit",
            ));
        }
        total_items = total_items.checked_add(list.len()).ok_or_else(|| {
            AppError::usage("TOO_MANY_ITEMS", "total input item count overflowed")
        })?;
        if list.iter().any(|item| item.len() > request.max_item_bytes) {
            return Err(AppError::usage(
                "ITEM_TOO_LARGE",
                "input item exceeds the configured byte limit",
            ));
        }
    }
    if total_items > request.max_total_items {
        return Err(AppError::usage(
            "TOO_MANY_ITEMS",
            "total input items exceed the configured limit",
        ));
    }
    if request.lean_jsonl && request.format != Format::Jsonl {
        return Err(AppError::usage(
            "FORMAT_UNSUPPORTED",
            "lean JSONL output requires the JSONL format",
        ));
    }
    if request.template.is_some() && request.template_file.is_some() {
        return Err(AppError::usage(
            "TEMPLATE_CONFLICT",
            "a template and template file cannot both be selected",
        ));
    }
    if request.shard_index.is_some() != request.shard_count.is_some() {
        return Err(AppError::usage(
            "SHARD_INVALID",
            "shard index and shard count must be provided together",
        ));
    }
    if matches!(
        request.operation,
        AppOperation::Permutations
            | AppOperation::Combinations { .. }
            | AppOperation::Variations { .. }
    ) && request.lists.len() != 1
    {
        return Err(AppError::usage(
            "ONE_LIST_REQUIRED",
            "this operation requires exactly one input list",
        ));
    }
    if request.names.len() > request.lists.len() {
        return Err(AppError::usage(
            "TEMPLATE_NAMES_MISMATCH",
            "more field names were provided than input lists",
        ));
    }
    Ok(())
}

fn prepared_lists(request: &ProductRequest) -> Result<Vec<Vec<String>>, AppError> {
    let mut lists = request.lists.clone();
    combinator_core::normalize_lists(
        &mut lists,
        &request.transforms,
        request.max_item_bytes,
        request.max_total_items,
    )
    .map_err(AppError::from)?;
    if let Some(template) = resolved_template(request)? {
        let parsed = combinator_codecs::Template::parse(&template)
            .map_err(|error| AppError::usage("TEMPLATE_INVALID", format!("{error:?}")))?;
        parsed
            .validate_fields(&request.names, lists.len())
            .map_err(|error| AppError::usage("TEMPLATE_INVALID", format!("{error:?}")))?;
    }
    Ok(lists)
}

fn resolved_template(request: &ProductRequest) -> Result<Option<String>, AppError> {
    if let Some(template) = &request.template {
        return Ok(Some(template.clone()));
    }
    let Some(path) = &request.template_file else {
        return Ok(None);
    };
    let bytes = std::fs::read(path).map_err(|error| {
        AppError::runtime(
            "TEMPLATE_FILE_UNREADABLE",
            format!("could not read template file: {error}"),
        )
    })?;
    if bytes.len() > request.max_item_bytes {
        return Err(AppError::usage(
            "TEMPLATE_TOO_LARGE",
            "template file exceeds the configured item byte limit",
        ));
    }
    String::from_utf8(bytes)
        .map(Some)
        .map_err(|_| AppError::usage("TEMPLATE_FILE_UNREADABLE", "template file is not UTF-8"))
}

fn parse_filters(expressions: &[String]) -> Result<Vec<Constraint>, AppError> {
    expressions
        .iter()
        .map(|expression| parse_filter(expression))
        .collect()
}

fn parse_filter(expression: &str) -> Result<Constraint, AppError> {
    let (head, value) = expression.split_once('=').ok_or_else(|| {
        AppError::usage("FILTER_INVALID", "filter must use KIND:FIELD=VALUE syntax")
    })?;
    let (kind, field) = head.split_once(':').ok_or_else(|| {
        AppError::usage(
            "FILTER_INVALID",
            "filter must include a numeric field index",
        )
    })?;
    let field = field
        .parse::<usize>()
        .map_err(|_| AppError::usage("FILTER_INVALID", "filter field index is invalid"))?;
    let constraint = match kind {
        "eq" | "equals" => Constraint::Equals {
            field,
            value: value.to_string(),
        },
        "neq" => Constraint::NotEquals {
            field,
            value: value.to_string(),
        },
        "prefix" => Constraint::Prefix {
            field,
            value: value.to_string(),
        },
        "suffix" => Constraint::Suffix {
            field,
            value: value.to_string(),
        },
        "glob" => Constraint::Glob {
            field,
            pattern: value.to_string(),
        },
        "length" => {
            let (min, max) = value.split_once("..").ok_or_else(|| {
                AppError::usage("FILTER_INVALID", "length filter must use MIN..MAX")
            })?;
            Constraint::Length {
                field,
                min: min
                    .parse()
                    .map_err(|_| AppError::usage("FILTER_INVALID", "length minimum is invalid"))?,
                max: max
                    .parse()
                    .map_err(|_| AppError::usage("FILTER_INVALID", "length maximum is invalid"))?,
            }
        }
        _ => return Err(AppError::usage("FILTER_INVALID", "unsupported filter kind")),
    };
    constraint.validate().map_err(AppError::from)?;
    Ok(constraint)
}

fn core_operation(request: &ProductRequest) -> Operation {
    match request.operation {
        AppOperation::Product { reverse_fields } => Operation::Product(ProductOptions {
            reverse_fields,
            ..request.options.clone()
        }),
        AppOperation::Zip { on_unequal } => Operation::Zip(ZipOptions {
            on_unequal,
            reverse: request.options.reverse,
            offset: request.options.offset,
            limit: request.options.limit,
        }),
        AppOperation::Concat => Operation::Concat(combinator_core::ConcatOptions {
            reverse: request.options.reverse,
            offset: request.options.offset,
            limit: request.options.limit,
        }),
        AppOperation::Permutations => Operation::Permutations(SelectionOptions {
            reverse: request.options.reverse,
            offset: request.options.offset,
            limit: request.options.limit,
        }),
        AppOperation::Combinations { choose } => Operation::Combinations {
            choose,
            options: SelectionOptions {
                reverse: request.options.reverse,
                offset: request.options.offset,
                limit: request.options.limit,
            },
        },
        AppOperation::Variations { length } => Operation::Variations {
            length,
            options: SelectionOptions {
                reverse: request.options.reverse,
                offset: request.options.offset,
                limit: request.options.limit,
            },
        },
    }
}

fn operation_selected_count(total: Count, operation: &Operation) -> u128 {
    let (offset, limit) = match operation {
        Operation::Product(options) => (options.offset, options.limit),
        Operation::Zip(options) => (options.offset, options.limit),
        Operation::Concat(options) => (options.offset, options.limit),
        Operation::Permutations(options) => (options.offset, options.limit),
        Operation::Combinations { options, .. } | Operation::Variations { options, .. } => {
            (options.offset, options.limit)
        }
    };
    match total {
        Count::Exact(total) => total.saturating_sub(offset).min(limit.unwrap_or(u128::MAX)),
        Count::Overflow => limit.unwrap_or(0),
    }
}

fn apply_shard(
    request: &ProductRequest,
    operation: Operation,
    total: Count,
) -> Result<Operation, AppError> {
    let (Some(index), Some(count)) = (request.shard_index, request.shard_count) else {
        return Ok(operation);
    };
    let total = match total {
        Count::Exact(value) => value,
        Count::Overflow => {
            return Err(AppError::usage(
                "SHARD_INVALID",
                "cannot shard an operation whose count overflowed",
            ))
        }
    };
    let range = combinator_core::sharding::range(total, index, count).map_err(|error| {
        AppError::usage("SHARD_INVALID", format!("invalid shard range: {error:?}"))
    })?;
    let (offset, limit) =
        combinator_core::sharding::page(range, request.options.offset, request.options.limit);
    Ok(with_window(operation, offset, Some(limit)))
}

fn with_window(operation: Operation, offset: u128, limit: Option<u128>) -> Operation {
    match operation {
        Operation::Product(options) => Operation::Product(ProductOptions {
            offset,
            limit,
            ..options
        }),
        Operation::Zip(options) => Operation::Zip(ZipOptions {
            offset,
            limit,
            ..options
        }),
        Operation::Concat(options) => Operation::Concat(combinator_core::ConcatOptions {
            offset,
            limit,
            ..options
        }),
        Operation::Permutations(options) => Operation::Permutations(SelectionOptions {
            offset,
            limit,
            ..options
        }),
        Operation::Combinations { choose, options } => Operation::Combinations {
            choose,
            options: SelectionOptions {
                offset,
                limit,
                ..options
            },
        },
        Operation::Variations { length, options } => Operation::Variations {
            length,
            options: SelectionOptions {
                offset,
                limit,
                ..options
            },
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn request() -> ProductRequest {
        ProductRequest {
            lists: vec![
                vec!["red".into(), "blue".into()],
                vec!["car".into(), "bike".into()],
            ],
            field_separator: "-".into(),
            ..Default::default()
        }
    }

    #[test]
    fn plan_reports_product_count_and_estimate() {
        let plan = plan(&request()).unwrap();
        assert_eq!(plan.total_combinations, Count::Exact(4));
        assert_eq!(plan.records_to_emit, 4);
        assert_eq!(plan.list_lengths, vec![2, 2]);
        assert!(matches!(plan.estimated_output_bytes, SizeEstimate::Bytes(value) if value > 0));
        assert!(plan.warnings.is_empty());
    }

    #[test]
    fn preview_uses_exact_output_order_and_format() {
        let records = preview(&request(), 3).unwrap();
        assert_eq!(
            records.iter().map(|r| r.value.as_str()).collect::<Vec<_>>(),
            ["red-car\n", "red-bike\n", "blue-car\n",]
        );
        assert_eq!(records[2].fields, vec!["blue", "car"]);
    }

    #[test]
    fn empty_list_is_a_warning_but_no_records() {
        let mut request = request();
        request.lists[1].clear();
        let plan = plan(&request).unwrap();
        assert_eq!(plan.total_combinations, Count::Exact(0));
        assert_eq!(plan.warnings[0].code, "EMPTY_LIST");
        assert!(execute(&request).unwrap().is_empty());
    }

    /// Concat still emits the non-empty lists, so the warning must not tell a
    /// GUI/TUI user that no records will be generated.
    #[test]
    fn concat_empty_list_warning_does_not_claim_no_records() {
        let mut request = request();
        request.operation = AppOperation::Concat;
        request.lists[1].clear();
        let plan = plan(&request).unwrap();
        assert_eq!(plan.total_combinations, Count::Exact(2));
        assert_eq!(plan.warnings[0].code, "EMPTY_LIST");
        assert!(
            !plan.warnings[0]
                .message
                .contains("no records will be generated"),
            "concat generates 2 records; warning said: {}",
            plan.warnings[0].message
        );
        assert_eq!(execute(&request).unwrap().len(), 2);
    }

    #[test]
    fn rejects_missing_lists_and_invalid_lean_format() {
        assert_eq!(
            plan(&ProductRequest::default()).unwrap_err().code,
            "NO_LISTS"
        );
        let mut request = request();
        request.lean_jsonl = true;
        assert_eq!(plan(&request).unwrap_err().code, "FORMAT_UNSUPPORTED");
    }

    #[test]
    fn enforces_output_byte_limit() {
        let mut request = request();
        request.max_output_bytes = 1;
        assert_eq!(execute(&request).unwrap_err().code, "OUTPUT_LIMIT_EXCEEDED");
    }

    #[test]
    fn loads_bounded_inline_and_file_sources() {
        let limits = InputLimits {
            max_input_bytes: 64,
            max_item_bytes: 16,
            max_items_per_list: 8,
        };
        let inline = read_input_source(
            &InputSource::Inline {
                value: "a,b".into(),
                delimiter: ",".into(),
            },
            limits,
        )
        .unwrap();
        assert_eq!(inline, ["a", "b"]);

        let path =
            std::env::temp_dir().join(format!("combinator-app-input-{}", std::process::id()));
        std::fs::write(&path, "x\ny\n").unwrap();
        let file = read_input_source(
            &InputSource::File {
                path: path.to_string_lossy().into_owned(),
                format: InputFormat::Lines,
            },
            limits,
        )
        .unwrap();
        assert_eq!(file, ["x", "y"]);
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn applies_transforms_before_template_rendering() {
        let mut request = request();
        request.lists = vec![vec![" B ".into(), "a".into()], vec!["x".into()]];
        request.transforms = vec!["trim".into(), "lower".into(), "sort".into()];
        request.template = Some("value={0}-{1}".into());
        let records = preview(&request, 2).unwrap();
        assert_eq!(records[0].value, "value=a-x\n");
        assert_eq!(records[1].value, "value=b-x\n");
    }

    #[test]
    fn streams_records_and_progress_without_collecting_in_the_app_layer() {
        struct Sink {
            records: Vec<OutputRecord>,
            progress: Vec<ProgressEvent>,
        }

        impl OutputSink for Sink {
            fn record(&mut self, record: OutputRecord) -> Result<(), AppError> {
                self.records.push(record);
                Ok(())
            }

            fn progress(&mut self, event: ProgressEvent) -> Result<(), AppError> {
                self.progress.push(event);
                Ok(())
            }
        }

        let mut sink = Sink {
            records: Vec::new(),
            progress: Vec::new(),
        };
        let progress = stream(&request(), &mut sink, None).unwrap();
        assert_eq!(progress.records, 4);
        assert_eq!(sink.records.len(), 4);
        assert_eq!(sink.progress.last(), Some(&progress));
    }

    #[test]
    fn streaming_honors_cancellation() {
        let cancel = || true;
        let mut records = Vec::new();
        struct Sink<'a> {
            records: &'a mut Vec<OutputRecord>,
        }
        impl OutputSink for Sink<'_> {
            fn record(&mut self, record: OutputRecord) -> Result<(), AppError> {
                self.records.push(record);
                Ok(())
            }
        }
        let mut sink = Sink {
            records: &mut records,
        };
        assert_eq!(
            stream(&request(), &mut sink, Some(&cancel))
                .unwrap_err()
                .code,
            "CANCELLED"
        );
        assert!(records.is_empty());
    }

    #[test]
    fn supports_zip_and_selection_operations() {
        let mut request = request();
        request.operation = AppOperation::Zip {
            on_unequal: UnequalPolicy::Error,
        };
        assert_eq!(preview(&request, 10).unwrap().len(), 2);
        request.lists = vec![vec!["a".into(), "b".into(), "c".into()]];
        request.operation = AppOperation::Combinations { choose: 2 };
        assert_eq!(preview(&request, 10).unwrap().len(), 3);
        request.operation = AppOperation::Variations { length: 2 };
        assert_eq!(preview(&request, 10).unwrap().len(), 6);
    }

    #[test]
    fn named_templates_are_rendered_and_validated() {
        let mut request = request();
        request.lists = vec![vec!["host".into()], vec!["443".into()]];
        request.names = vec!["host".into(), "port".into()];
        request.template = Some("{host}:{port}".into());
        let records = preview(&request, 1).unwrap();
        assert_eq!(records[0].value, "host:443\n");
    }

    #[test]
    fn typed_filters_limit_streamed_records() {
        let mut request = request();
        request.filters = vec!["prefix:0=b".into()];
        let records = preview(&request, 10).unwrap();
        assert_eq!(records.len(), 2);
        assert!(records.iter().all(|record| record.fields[0] == "blue"));
    }

    #[test]
    fn not_equal_filters_exclude_matching_records() {
        let mut request = request();
        request.filters = vec!["neq:0=blue".into()];
        let records = preview(&request, 10).unwrap();
        assert_eq!(records.len(), 2);
        assert!(records.iter().all(|record| record.fields[0] != "blue"));
    }

    #[test]
    fn template_file_is_bounded_and_rendered() {
        let path =
            std::env::temp_dir().join(format!("combinator-app-template-{}", std::process::id()));
        std::fs::write(&path, "{0}/{1}").unwrap();
        let mut request = request();
        request.template_file = Some(path.to_string_lossy().into_owned());
        let records = preview(&request, 1).unwrap();
        assert_eq!(records[0].value, "red/car\n");
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn shard_window_selects_contiguous_records() {
        let mut request = request();
        request.shard_index = Some(1);
        request.shard_count = Some(2);
        let records = preview(&request, 10).unwrap();
        assert_eq!(
            records
                .iter()
                .map(|record| record.value.as_str())
                .collect::<Vec<_>>(),
            vec!["blue-car\n", "blue-bike\n"]
        );
    }
}
